app:
  database-access-type: jooq
  gitUrl: "https://api.github.com"
  stackUrl: "https://api.stackexchange.com/2.3"
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 30s
  retryOn: server-client
  retry-strategy: const
  retry-max-attempts: 3
  retry-delay: 5
  refill: 5
  capacity: 10
  timeout: 1

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    hikari:
      username: postgres
      password: postgres
      jdbc-url: jdbc:postgresql://localhost:5432/scrapper
      driver-class-name: org.postgresql.Driver

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
