app:
  use-queue: true
  database-access-type: jooq
  gitUrl: "https://api.github.com"
  stackUrl: "https://api.stackexchange.com/2.3"
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 30s
  retry:
    trigger: server-client
    strategy: const
    max-attempts: 3
    delay: 5
  bucket:
    refill: 5
    capacity: 10
    timeout: 1
  kafka:
    partitions-num: 10
    replicas-num: 1
    topics: topic1

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    hikari:
      username: postgres
      password: postgres
      jdbc-url: jdbc:postgresql://localhost:5432/scrapper
      driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Для строковых ключей
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.value.default.type: edu.java.model.request.LinkUpdateRequest
    bootstrapServers: localhost:29092

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
