app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: postgres
    username: postgres

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
