app:
  telegram-token: ${TELEGRAM_API_KEY}
  kafka:
    partitions-num: 10
    replicas-num: 1
    topics: topic1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrapServers: localhost:29092

server:
  port: 8090

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
