/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.SofLinkPropertiesRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SofLinkProperties extends TableImpl<SofLinkPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SOF_LINK_PROPERTIES</code>
     */
    public static final SofLinkProperties SOF_LINK_PROPERTIES = new SofLinkProperties();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<SofLinkPropertiesRecord> getRecordType() {
        return SofLinkPropertiesRecord.class;
    }

    /**
     * The column <code>SOF_LINK_PROPERTIES.ID</code>.
     */
    public final TableField<SofLinkPropertiesRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>SOF_LINK_PROPERTIES.LINK_ID</code>.
     */
    public final TableField<SofLinkPropertiesRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SOF_LINK_PROPERTIES.ANSWER_COUNT</code>.
     */
    public final TableField<SofLinkPropertiesRecord, Long> ANSWER_COUNT = createField(DSL.name("ANSWER_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SOF_LINK_PROPERTIES.COMMENT_COUNT</code>.
     */
    public final TableField<SofLinkPropertiesRecord, Long> COMMENT_COUNT = createField(DSL.name("COMMENT_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    private SofLinkProperties(Name alias, Table<SofLinkPropertiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SofLinkProperties(Name alias, Table<SofLinkPropertiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SOF_LINK_PROPERTIES</code> table reference
     */
    public SofLinkProperties(String alias) {
        this(DSL.name(alias), SOF_LINK_PROPERTIES);
    }

    /**
     * Create an aliased <code>SOF_LINK_PROPERTIES</code> table reference
     */
    public SofLinkProperties(Name alias) {
        this(alias, SOF_LINK_PROPERTIES);
    }

    /**
     * Create a <code>SOF_LINK_PROPERTIES</code> table reference
     */
    public SofLinkProperties() {
        this(DSL.name("SOF_LINK_PROPERTIES"), null);
    }

    public <O extends Record> SofLinkProperties(Table<O> child, ForeignKey<O, SofLinkPropertiesRecord> key) {
        super(child, key, SOF_LINK_PROPERTIES);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<SofLinkPropertiesRecord, Long> getIdentity() {
        return (Identity<SofLinkPropertiesRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<SofLinkPropertiesRecord> getPrimaryKey() {
        return Keys.PK_SOF_LINK_PROPERTIES;
    }

    @Override
    @NotNull
    public SofLinkProperties as(String alias) {
        return new SofLinkProperties(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public SofLinkProperties as(Name alias) {
        return new SofLinkProperties(alias, this);
    }

    @Override
    @NotNull
    public SofLinkProperties as(Table<?> alias) {
        return new SofLinkProperties(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SofLinkProperties rename(String name) {
        return new SofLinkProperties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SofLinkProperties rename(Name name) {
        return new SofLinkProperties(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SofLinkProperties rename(Table<?> name) {
        return new SofLinkProperties(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
