/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SofLinkProperties implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long linkId;
    private Long answerCount;
    private Long commentCount;

    public SofLinkProperties() {}

    public SofLinkProperties(SofLinkProperties value) {
        this.id = value.id;
        this.linkId = value.linkId;
        this.answerCount = value.answerCount;
        this.commentCount = value.commentCount;
    }

    @ConstructorProperties({ "id", "linkId", "answerCount", "commentCount" })
    public SofLinkProperties(
        @NotNull Long id,
        @NotNull Long linkId,
        @NotNull Long answerCount,
        @NotNull Long commentCount
    ) {
        this.id = id;
        this.linkId = linkId;
        this.answerCount = answerCount;
        this.commentCount = commentCount;
    }

    /**
     * Getter for <code>SOF_LINK_PROPERTIES.ID</code>.
     */
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>SOF_LINK_PROPERTIES.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>SOF_LINK_PROPERTIES.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>SOF_LINK_PROPERTIES.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>SOF_LINK_PROPERTIES.ANSWER_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>SOF_LINK_PROPERTIES.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@NotNull Long answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>SOF_LINK_PROPERTIES.COMMENT_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCommentCount() {
        return this.commentCount;
    }

    /**
     * Setter for <code>SOF_LINK_PROPERTIES.COMMENT_COUNT</code>.
     */
    public void setCommentCount(@NotNull Long commentCount) {
        this.commentCount = commentCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SofLinkProperties other = (SofLinkProperties) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        if (this.commentCount == null) {
            if (other.commentCount != null)
                return false;
        }
        else if (!this.commentCount.equals(other.commentCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        result = prime * result + ((this.commentCount == null) ? 0 : this.commentCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SofLinkProperties (");

        sb.append(id);
        sb.append(", ").append(linkId);
        sb.append(", ").append(answerCount);
        sb.append(", ").append(commentCount);

        sb.append(")");
        return sb.toString();
    }
}
