/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.SofLinkProperties;
import edu.java.domain.jooq.tables.records.ChatRecord;
import edu.java.domain.jooq.tables.records.LinkRecord;
import edu.java.domain.jooq.tables.records.SofLinkPropertiesRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> PK_CHAT = Internal.createUniqueKey(Chat.CHAT, DSL.name("PK_CHAT"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<LinkRecord> PK_LINK = Internal.createUniqueKey(Link.LINK, DSL.name("PK_LINK"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<SofLinkPropertiesRecord> PK_SOF_LINK_PROPERTIES = Internal.createUniqueKey(SofLinkProperties.SOF_LINK_PROPERTIES, DSL.name("PK_SOF_LINK_PROPERTIES"), new TableField[] { SofLinkProperties.SOF_LINK_PROPERTIES.ID }, true);
}
